#include "web_ui_page.h"
#include "sd_storage.h"

static const char s_web_ui_index[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><title>SceneHub</title>"
        "<style>"
        ":root{--bg:#08090b;--bg2:#0c0e12;--side:#0d0f12;--panel:#12151a;--panel2:#171b21;--panel3:#1d2229;--line:#2a3038;--line-soft:#222831;--text:#eef2f6;--muted:#8d99a6;--muted2:#6f7883;--accent:#f0b43a;--accent-soft:rgba(240,180,58,.14);--good:#35d07f;--warn:#ff9f43;--bad:#ff5a5f;--shadow:0 18px 40px rgba(0,0,0,.34);--shadow-soft:0 10px 24px rgba(0,0,0,.24);--radius:8px;--radius-sm:6px;}"
        "body{margin:0;padding:0;font-family:'Segoe UI',Tahoma,sans-serif;background:radial-gradient(circle at top,#12141a 0%,#0b0c10 26%,#08090b 64%,#07080a 100%);color:var(--text);display:flex;justify-content:center;}"
        ".page{width:100%;max-width:1400px;margin:0 auto;padding:24px 0 28px;}"
        ".tabs{display:flex;flex-wrap:wrap;gap:10px;padding:0;margin:0;justify-content:center;}"
        ".tab{height:38px;min-width:110px;padding:0 16px;border-radius:var(--radius-sm);cursor:pointer;border:1px solid transparent;background:#141820;color:var(--text);font-weight:600;display:inline-flex;align-items:center;justify-content:center;gap:8px;font-size:13px;transition:transform .15s ease,box-shadow .2s ease,opacity .2s ease,border-color .2s ease,background .2s ease;position:relative;box-shadow:inset 0 1px 0 rgba(255,255,255,.02);}"
        ".tab:not(.active){opacity:.9;}"
        ".tab.active{transform:translateY(-1px);border-color:rgba(240,180,58,.55);background:linear-gradient(180deg,#191c22,#14171c);box-shadow:0 0 0 1px rgba(240,180,58,.16),0 12px 28px rgba(0,0,0,.35);}"
        ".tab .tab-icon{width:20px;height:20px;border-radius:8px;background:rgba(11,13,19,0.15);display:inline-flex;align-items:center;justify-content:center;background-repeat:no-repeat;background-position:center;background-size:16px;color:#0b0d13;flex-shrink:0;}"
        ".tab .tab-label{white-space:nowrap;}"
        ".tab[data-icon='status'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpolyline%20points%3D%273%2012%207%2012%2010%206%2014%2018%2017%2012%2021%2012%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='audio'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpolygon%20points%3D%275%209%209%209%2013%205%2013%2019%209%2015%205%2015%205%209%27%2F%3E%3Cpath%20d%3D%27M16%209c1.5%201.5%201.5%204.5%200%206%27%2F%3E%3Cpath%20d%3D%27M19%207c2.5%202.5%202.5%207.5%200%2010%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='settings'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Ccircle%20cx%3D%2712%27%20cy%3D%2712%27%20r%3D%273%27%2F%3E%3Cpath%20d%3D%27M19.4%2015a1.65%201.65%200%200%200%20.33%201.82l.06.06a2%202%200%200%201-2.83%202.83l-.06-.06a1.65%201.65%200%200%200-1.82-.33%201.65%201.65%200%200%200-1%201.51V21a2%202%200%200%201-4%200v-.09A1.65%201.65%200%200%200%209%2019.4a1.65%201.65%200%200%200-1.82.33l-.06.06a2%202%200%200%201-2.83-2.83l.06-.06a1.65%201.65%200%200%200%20.33-1.82%201.65%201.65%200%200%200-1.51-1H3a2%202%200%200%201%200-4h.09A1.65%201.65%200%200%200%204.6%209%201.65%201.65%200%200%200%204.27%207.18l-.06-.06A2%202%200%200%201%207.04%204.3l.06.06A1.65%201.65%200%200%200%208.91%204a1.65%201.65%200%200%200%201-1.51V3a2%202%200%200%201%204%200v.09A1.65%201.65%200%200%200%2015%204.6a1.65%201.65%200%200%200%201.82-.33l.06-.06a2%202%200%200%201%202.83%202.83l-.06.06A1.65%201.65%200%200%200%2019.74%209%201.65%201.65%200%200%200%2021.25%2010H21a2%202%200%200%201%200%204h-.09a1.65%201.65%200%200%200-1.51%201z%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='devices'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpath%20d%3D%27M12%201V7%27/%3E%3Crect%20x%3D%275%27%20y%3D%279%27%20width%3D%2714%27%20height%3D%2711%27%20rx%3D%272%27/%3E%3Cpath%20d%3D%27M8%2020v3h8v-3%27/%3E%3Cpath%20d%3D%27M8%2013h8%27/%3E%3Ccircle%20cx%3D%2212%22%20cy%3D%2216%22%20r%3D%221%22/%3E%3C/svg%3E\");}"
        ".tab[data-icon='network'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpath%20d%3D%27M5%2012a9%209%200%200%201%2014%200%27%2F%3E%3Cpath%20d%3D%27M8.5%2015.5a5%205%200%200%201%207%200%27%2F%3E%3Cpath%20d%3D%27M12%2019h.01%27%2F%3E%3C%2Fsvg%3E\");}"
        ".tab[data-icon='power'] .tab-icon{background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25230b0d13%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cline%20x1%3D%2712%27%20y1%3D%272%27%20x2%3D%2712%27%20y2%3D%2712%27%2F%3E%3Cpath%20d%3D%27M5.5%207.5a7%207%200%201%200%2013%200%27%2F%3E%3C%2Fsvg%3E\");}"
        ".pane{padding:24px;display:none;max-width:1200px;margin:0 auto;} .pane.active{display:block;}"
".card{background:linear-gradient(180deg,var(--panel2),var(--panel));border:1px solid var(--line-soft);border-radius:var(--radius);padding:18px;margin:0 auto 14px;box-shadow:var(--shadow-soft);}"
".dx-editor-pane{display:none;}"
".dx-editor-pane.active{display:block;}"
"h3,h4{margin:0 0 10px;color:var(--text);font-weight:700;letter-spacing:.02em;}"
        "input,select{background:#0f1217;border:1px solid var(--line);color:var(--text);border-radius:var(--radius-sm);padding:10px 12px;margin:4px 8px 4px 0;min-width:220px;box-shadow:inset 0 1px 0 rgba(255,255,255,.02);}"
        "input:focus,select:focus{outline:none;border-color:rgba(240,180,58,.5);box-shadow:0 0 0 3px rgba(240,180,58,.08);}"
        "button:not(.icon-btn){background:linear-gradient(180deg,#222730,#171b21);border:1px solid var(--line);color:var(--text);border-radius:var(--radius-sm);padding:10px 15px;margin:4px 8px 4px 0;cursor:pointer;font-weight:700;box-shadow:var(--shadow-soft);transition:background .2s ease,border-color .2s ease,transform .15s ease,box-shadow .2s ease;}button:not(.icon-btn):hover{background:linear-gradient(180deg,#272d37,#1a1f26);border-color:rgba(240,180,58,.4);transform:translateY(-1px);}button:not(.icon-btn):active{transform:translateY(0);}"
        ".muted{color:var(--muted);font-size:13px;}"
        ".row{display:flex;flex-wrap:wrap;align-items:center;}"
        ".mqtt-user-row{display:flex;flex-wrap:wrap;align-items:center;gap:8px;margin:6px 0;}"
        ".mqtt-user-row input{flex:1 1 140px;min-width:150px;}"
        ".mqtt-user-row button{flex:0 0 auto;}"
        ".controls-row{display:flex;align-items:center;gap:16px;flex-wrap:wrap;}"
        ".volume-control{display:flex;align-items:center;gap:10px;min-width:200px;flex:1 1 200px;}"
        ".volume-control input{max-width:220px;}"
        ".control-buttons{display:flex;gap:10px;flex-shrink:0;}"
        ".mode-row{gap:10px;}"
        ".mode-btn{min-width:120px;font-weight:700;border:1px solid var(--line);background:#11151b;color:#d6dde5;border-radius:var(--radius-sm);padding:10px 14px;cursor:pointer;transition:box-shadow .2s ease,border-color .2s ease,color .2s ease,background .2s ease;}"
        ".mode-btn.active{border-color:rgba(240,180,58,.52);background:linear-gradient(180deg,#1a1d23,#13161b);color:#fff;box-shadow:0 0 0 1px rgba(240,180,58,.18),0 10px 26px rgba(0,0,0,.34);}"
        ".mode-btn.mode-last{box-shadow:0 0 0 1px rgba(240,180,58,.35),0 0 18px rgba(240,180,58,.18);}"
        ".progress-box{border:1px solid rgba(240,180,58,.22);border-radius:var(--radius);background:linear-gradient(180deg,#151920,#101319);padding:12px 14px;margin-top:10px;display:flex;flex-direction:column;gap:6px;box-shadow:var(--shadow-soft);color:var(--text);}"
        ".progress-row{display:flex;flex-direction:column;align-items:stretch;gap:2px;}"
        ".progress-row input{flex:0 0 auto;min-width:220px;width:100%;}"
        ".progress-row .muted{font-size:12px;}"
        "input[type=range]{-webkit-appearance:none;appearance:none;padding:0;background:transparent;border:none;min-width:0;height:24px;display:block;margin:4px 0;}"
        "input[type=range]:focus{outline:none;}"
        "input[type=range]::-webkit-slider-runnable-track{width:100%;height:6px;background:#1b2027;border-radius:999px;border:1px solid var(--line-soft);}"
        "input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;appearance:none;width:14px;height:14px;border-radius:50%;background:var(--accent);border:2px solid #0b0d13;margin-top:-5px;box-shadow:0 0 0 2px rgba(240,180,58,.2);cursor:pointer;}"
        "input[type=range]::-moz-range-track{width:100%;height:6px;background:#1b2027;border-radius:999px;border:1px solid var(--line-soft);}"
        "input[type=range]::-moz-range-thumb{width:14px;height:14px;border-radius:50%;background:var(--accent);border:2px solid #0b0d13;cursor:pointer;}"
        "input[type=range]::-ms-track{width:100%;height:6px;background:transparent;border-color:transparent;color:transparent;}"
        "input[type=range]::-ms-fill-lower{background:#1b2027;border-radius:999px;border:1px solid var(--line-soft);}"
        "input[type=range]::-ms-fill-upper{background:#1b2027;border-radius:999px;border:1px solid var(--line-soft);}"
        "input[type=range]::-ms-thumb{width:14px;height:14px;border-radius:50%;background:var(--accent);border:2px solid #0b0d13;cursor:pointer;margin-top:0;}"
        ".list{margin:6px 0;}"
        ".pill{display:inline-block;padding:6px 10px;border-radius:999px;background:#1a1f27;border:1px solid var(--line-soft);margin:4px;color:#d6dde5;font-size:13px;cursor:pointer;}"
        ".badge{display:inline-block;padding:6px 10px;border-radius:999px;background:#1a1f27;border:1px solid var(--line-soft);margin-left:8px;font-size:12px;}"
        ".hero{padding:16px 20px;background:linear-gradient(180deg,var(--panel2),var(--panel));border:1px solid var(--line-soft);border-radius:var(--radius);margin:0 auto 12px;max-width:1200px;display:grid;grid-template-columns:minmax(160px,auto) minmax(0,1fr) auto;align-items:center;gap:16px;box-shadow:var(--shadow-soft);}"
        ".hero h2{margin:0;font-weight:800;color:var(--text);letter-spacing:.01em;}"
        ".hero-brand{display:flex;align-items:center;justify-content:flex-start;min-width:160px;}"
        ".hero-center{min-width:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;}"
        ".hero-banner{text-align:center;max-width:100%;}"
        ".gm-entry{height:40px;padding:0 16px;border-radius:var(--radius-sm);background:linear-gradient(180deg,#1f9d52,#16793d);color:#fff;text-decoration:none;font-weight:800;display:inline-flex;align-items:center;justify-content:center;box-shadow:0 10px 24px rgba(22,121,61,.24);border:1px solid rgba(53,208,127,.35);}"
        ".gm-entry:hover{background:linear-gradient(180deg,#239f55,#198643);}"
        ".hero .status-clusters{display:flex;gap:16px;align-items:center;flex-wrap:wrap;margin-left:auto;}"
        ".device-cluster{display:flex;align-items:center;gap:6px;background:#10141a;border:1px solid var(--line-soft);padding:6px 10px;border-radius:var(--radius-sm);min-width:110px;justify-content:center;}"
        ".device-cluster .label{font-size:12px;color:var(--muted);display:flex;align-items:center;gap:4px;}"
        ".device-cluster .dots{display:flex;gap:4px;}"
        ".device-cluster .dots span{width:10px;height:10px;border-radius:50%;background:#1f2937;}"
        ".device-icon{font-size:16px;}"
        ".stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;margin-top:12px;}"
        ".stat{background:#0f1217;border:1px solid var(--line);border-radius:var(--radius-sm);padding:10px 12px;box-shadow:inset 0 1px 0 rgba(255,255,255,.02);}"
        ".stat .label{display:block;color:var(--muted);font-size:12px;margin-bottom:4px;text-transform:none;}"
        ".stat .value{font-weight:700;color:var(--text);}"
        ".dots span{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:4px;background:#1f2937;}"
".small{font-size:12px;}"
".status-row{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin:6px 0;}"
".sequence-monitor{display:flex;flex-direction:column;gap:12px;}"
".sequence-device{border:1px solid var(--line);border-radius:var(--radius-sm);padding:10px;background:#0f1217;}"
".sequence-device h4{margin:0 0 8px;font-size:15px;color:#f1f5f9;}"
".sequence-meta{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:8px;}"
".sequence-pill{display:inline-flex;align-items:center;gap:6px;padding:5px 8px;border-radius:999px;background:#141920;border:1px solid var(--line-soft);color:#d6dde5;font-size:12px;}"
".sequence-details{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;}"
".sequence-detail{border:1px dashed var(--line);border-radius:var(--radius-sm);padding:6px 8px;background:#0a0d12;color:#e5e7eb;font-size:12px;}"
".sequence-detail .label{display:block;color:var(--muted);font-size:11px;margin-bottom:2px;}"
        ".file-browser{margin-top:12px;border:1px solid rgba(240,180,58,.16);background:linear-gradient(180deg,#13171d,#0e1116);border-radius:var(--radius);padding:18px;max-width:1320px;margin-left:auto;margin-right:auto;box-shadow:var(--shadow);}"
        ".audio-browser-toolbar{display:grid;grid-template-columns:auto minmax(0,1fr) minmax(240px,320px);gap:12px;align-items:center;margin-bottom:12px;}"
        ".audio-nav-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center;}"
        ".audio-nav-actions button{margin:0;}"
        ".audio-breadcrumbs{min-height:40px;display:flex;flex-wrap:wrap;align-items:center;gap:6px;padding:8px 10px;border:1px solid var(--line);border-radius:var(--radius-sm);background:#101319;}"
        ".audio-breadcrumb{display:inline-flex;align-items:center;justify-content:center;min-height:28px;padding:0 10px;border:1px solid transparent;border-radius:999px;background:#171b22;color:var(--text);font-size:12px;font-weight:700;cursor:pointer;transition:border-color .2s ease,background .2s ease,color .2s ease;}"
        ".audio-breadcrumb:hover{border-color:rgba(240,180,58,.4);}"
        ".audio-breadcrumb.active{background:linear-gradient(180deg,#1f231c,#161910);border-color:rgba(240,180,58,.5);color:#fff;}"
        ".audio-breadcrumb-sep{color:var(--muted2);font-size:12px;}"
        ".audio-search-wrap input{width:100%;min-width:0;margin:0;}"
        ".audio-browser-grid{display:grid;grid-template-columns:320px minmax(0,1fr);gap:12px;align-items:stretch;}"
        ".audio-browser-section{border:1px solid var(--line);border-radius:var(--radius);background:#101319;padding:12px;height:656px;min-height:656px;box-shadow:inset 0 1px 0 rgba(255,255,255,.02);display:flex;flex-direction:column;overflow:hidden;}"
        ".audio-section-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:10px;}"
        ".audio-section-head h4{margin:0;font-size:14px;}"
        ".folder-row{display:flex;flex:1 1 auto;flex-direction:column;gap:8px;margin:0;width:100%;justify-content:flex-start;min-height:0;align-items:stretch;overflow-y:auto;padding-right:4px;scrollbar-gutter:stable;scrollbar-width:thin;scrollbar-color:#303844 #0d1016;}"
        ".folder-chip{width:100%;min-height:52px;border:1px solid var(--line);border-radius:var(--radius);background:linear-gradient(180deg,#171b22,#101319);cursor:pointer;font-size:13px;color:var(--text);display:flex;align-items:center;justify-content:flex-start;box-sizing:border-box;overflow:hidden;text-align:left;font-weight:700;letter-spacing:.02em;text-transform:none;box-shadow:var(--shadow-soft);padding:0 14px;}"
        ".folder-chip:hover{border-color:rgba(240,180,58,.42);box-shadow:0 12px 28px rgba(0,0,0,.34);}"
        ".folder-chip.active{box-shadow:0 0 0 1px rgba(240,180,58,.32),0 16px 36px rgba(0,0,0,.4);background:linear-gradient(180deg,#1d211f,#141711);border-color:rgba(240,180,58,.58);}"
        ".file-grid{margin:0;width:100%;max-width:none;min-height:0;}"
        ".audio-track-grid{display:grid;flex:1 1 auto;grid-template-columns:repeat(5,minmax(0,1fr));grid-auto-rows:108px;gap:10px;min-height:0;height:100%;overflow-y:auto;padding-right:4px;scrollbar-gutter:stable;scrollbar-width:thin;scrollbar-color:#303844 #0d1016;align-content:start;}"
        ".audio-track-grid .track-card{width:100%;min-height:108px;height:108px;border-radius:var(--radius-sm);display:flex;align-items:flex-end;justify-content:flex-start;position:relative;overflow:hidden;color:var(--text);border:1px solid var(--line-soft);background:linear-gradient(180deg,#171b22,#11151b);cursor:pointer;box-shadow:none;z-index:1;transition:border-color .18s ease,background .18s ease,transform .12s ease;box-sizing:border-box;padding:0 12px 10px;gap:10px;}"
        ".audio-track-grid .track-card::before{content:'';position:absolute;top:12px;left:12px;width:18px;height:18px;flex:0 0 18px;background-image:url(\"data:image/svg+xml,%3Csvg%20xmlns%3D%27http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%27%20viewBox%3D%270%200%2024%2024%27%20stroke%3D%27%25238d99a6%27%20stroke-width%3D%272%27%20fill%3D%27none%27%20stroke-linecap%3D%27round%27%20stroke-linejoin%3D%27round%27%3E%3Cpolygon%20points%3D%275%209%209%209%2013%205%2013%2019%209%2015%205%2015%205%209%27%2F%3E%3Cpath%20d%3D%27M16%209c1.5%201.5%201.5%204.5%200%206%27%2F%3E%3Cpath%20d%3D%27M19%207c2.5%202.5%202.5%207.5%200%2010%27%2F%3E%3C%2Fsvg%3E\");background-size:contain;background-repeat:no-repeat;background-position:center;opacity:.92;}"
        ".audio-track-grid .track-card:hover{border-color:rgba(240,180,58,.32);background:linear-gradient(180deg,#1a1f26,#13171d);transform:translateY(-1px);}"
        ".audio-track-grid .track-card.selected{border-color:rgba(240,180,58,.58);box-shadow:0 0 0 1px rgba(240,180,58,.2) inset;background:linear-gradient(180deg,#1e211d,#151912);}"
        ".audio-track-grid .track-card.playing{border-color:rgba(53,208,127,.42);background:linear-gradient(180deg,#18211b,#121914);box-shadow:0 0 0 1px rgba(53,208,127,.16) inset;}"
        ".audio-track-grid .track-card.playing::before{filter:hue-rotate(48deg) saturate(1.3);}"
        ".track-name{flex:1 1 auto;min-width:0;max-width:100%;color:#f8fafc;font-weight:600;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;letter-spacing:0.01em;align-self:flex-end;}"
        ".track-meta{position:absolute;top:10px;right:10px;flex:0 0 auto;font-size:11px;font-weight:700;color:var(--muted);padding:4px 8px;border-radius:999px;border:1px solid var(--line);background:#0e1217;text-transform:uppercase;letter-spacing:.06em;}"
        ".audio-empty{display:flex;align-items:center;justify-content:center;flex:1 1 auto;min-height:120px;padding:16px;border:1px dashed var(--line);border-radius:var(--radius-sm);color:var(--muted);font-size:13px;text-align:center;background:#0d1016;}"
        ".folder-row::-webkit-scrollbar,.audio-track-grid::-webkit-scrollbar{width:10px;}"
        ".folder-row::-webkit-scrollbar-track,.audio-track-grid::-webkit-scrollbar-track{background:#0d1016;border-radius:999px;}"
        ".folder-row::-webkit-scrollbar-thumb,.audio-track-grid::-webkit-scrollbar-thumb{background:linear-gradient(180deg,#2d3540,#20262f);border:2px solid #0d1016;border-radius:999px;}"
        ".folder-row::-webkit-scrollbar-thumb:hover,.audio-track-grid::-webkit-scrollbar-thumb:hover{background:linear-gradient(180deg,#3b4551,#29313c);}"
        ".icon-btn{width:36px;height:36px;border:1px solid var(--line);border-radius:var(--radius-sm);background:linear-gradient(180deg,#181c22,#12161b);color:#f1f5f9;display:inline-flex;align-items:center;justify-content:center;cursor:pointer;margin-left:12px;position:relative;box-shadow:var(--shadow-soft);}"
        ".icon-btn::before{content:'';display:block;width:14px;height:14px;}"
        ".icon-btn:hover{border-color:rgba(240,180,58,.42);color:#fff;box-shadow:0 14px 30px rgba(0,0,0,.42);}"
        ".icon-btn.active{border-color:rgba(240,180,58,.55);box-shadow:0 0 0 1px rgba(240,180,58,.2),0 16px 32px rgba(0,0,0,.44);background:linear-gradient(180deg,#211b11,#17130f);color:#f8fafc;}"
        ".icon-btn.icon-stop::before{width:12px;height:12px;background:#f87171;border-radius:3px;}"
        ".icon-btn.icon-pause::before{background:linear-gradient(90deg,#cbd5e1 0,#cbd5e1 40%,transparent 40%,transparent 60%,#cbd5e1 60%,#cbd5e1 100%);}"
        ".icon-btn.icon-play::before{content:'';width:0;height:0;border-left:12px solid #cbd5e1;border-top:6px solid transparent;border-bottom:6px solid transparent;margin-left:2px;}"
        ".icon-btn.icon-repeat::before{background-image:url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' stroke='%23cbd5e1' stroke-width='2' fill='none' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='17 1 21 5 17 9'/%3E%3Cpath d='M3 11V9a4 4 0 0 1 4-4h14'/%3E%3Cpolyline points='7 23 3 19 7 15'/%3E%3Cpath d='M21 13v2a4 4 0 0 1-4 4H3'/%3E%3C/svg%3E\");background-size:contain;background-repeat:no-repeat;}"
        "table{width:100%;border-collapse:collapse;margin-top:10px;}"
        "td,th{border:1px solid var(--line);padding:8px;}"
        "@media(max-width:980px){.audio-browser-toolbar{grid-template-columns:1fr;}.audio-browser-grid{grid-template-columns:1fr;}.audio-browser-section{min-height:0;height:auto;}.audio-track-grid{grid-template-columns:repeat(5,minmax(0,1fr));}}"
        "@media(max-width:800px){.page{padding-top:16px;} .hero{grid-template-columns:1fr;justify-items:center;text-align:center;} .hero-brand{justify-content:center;} .hero-center{width:100%;} .tabs{width:100%;} .gm-entry{width:100%;max-width:260px;}}"
        "@media(max-width:600px){.pane{padding:16px;width:100%;} .card{margin:0 0 12px;width:100%;padding:14px;} .hero{margin:0 0 12px;padding:14px;} .row{flex-direction:column;align-items:stretch;} .row button,.row select,.row input{width:100%;max-width:100%;} .controls-row{flex-direction:column;align-items:stretch;} .control-buttons{justify-content:space-between;} .volume-control{width:100%;} .progress-row input{max-width:100%;} .file-browser{padding:12px;} .audio-track-grid{grid-template-columns:repeat(2,minmax(0,1fr));} .tab{min-width:88px;height:36px;flex:1 1 calc(50% - 10px);}}"
"</style></head><body>"
        "<div class='page'>"
        "<div class='hero'><div class='hero-brand'><h2>SceneHub</h2></div><div class='hero-center'><div class='tabs'>"
"<div class='tab active' data-tab='status' data-icon='status'><span class='tab-icon'></span><span class='tab-label'>Status</span></div>"
"<div class='tab' data-tab='audio' data-icon='audio'><span class='tab-icon'></span><span class='tab-label'>Audio</span></div>"
"<div class='tab' data-tab='settings' data-icon='settings'><span class='tab-icon'></span><span class='tab-label'>Settings</span></div>"
"<div class='tab' data-tab='update' data-icon='settings'><span class='tab-icon'></span><span class='tab-label'>Update</span></div>"
"</div><div id='banner' class='muted hero-banner'>Loading status...</div></div><a class='gm-entry' href='/gm'>Open GM Panel</a></div>"
        "<div class='pane active' id='pane-status'>"
"<div class='card'><h3>Status<span id='status_badge' class='badge'></span></h3>"
        "<div class='status-row'><button onclick='ping()'>Ping</button><button onclick='loadStatus()'>Refresh</button><button id='status_raw_btn' onclick='toggleRaw()'>Show raw</button><span id='status_state' class='muted'>Loading...</span></div>"
        "<div class='stat-grid'>"
"<div class='stat'><span class='label'>Wi-Fi SSID</span><span id='status_ssid' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>STA IP</span><span id='status_ip' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>SD Size</span><span id='status_sd_size' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>Clients total</span><span id='status_clients' class='value'>0</span></div>"
"<div class='stat'><span class='label'>RAM free</span><span id='status_ram' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>PSRAM free</span><span id='status_psram' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>Services</span><span id='status_services' class='value'>n/a</span></div>"
"</div>"
"<pre id='status_raw' class='muted small' style='display:none;'></pre>"
"</div>"
"</div>"
"<div class='pane' id='pane-update'>"
"<div class='card'><h3>Firmware Update</h3>"
"<div class='stat-grid'>"
"<div class='stat'><span class='label'>Version</span><span id='ota_version' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>Running slot</span><span id='ota_running' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>Boot slot</span><span id='ota_boot' class='value'>n/a</span></div>"
"<div class='stat'><span class='label'>State</span><span id='ota_state' class='value'>n/a</span></div>"
"</div>"
"<div id='ota_last_error' class='muted small' style='margin-top:10px;'>No OTA errors.</div>"
"<div id='ota_phase_hint' class='muted small' style='margin-top:8px;'>Idle. You can upload a new firmware image.</div>"
"<div class='row' style='margin-top:10px;'><input id='ota_file' type='file' accept='.bin,application/octet-stream'><button id='ota_upload_btn' onclick='uploadFirmware()'>Upload firmware</button><button id='ota_reboot_btn' onclick='requestOtaReboot()' disabled>Reboot now</button><button id='ota_refresh_btn' onclick='refreshOtaStatus()'>Refresh OTA</button></div>"
"<div id='ota_upload_status' class='muted small'>Idle.</div>"
"<div class='muted small'>Upload the raw .bin image for this board. Reboot is requested separately after a successful install.</div>"
"</div>"
"</div>"

        "<div class='pane' id='pane-audio'>"
        "<div class='card'><h3>Audio</h3>"
        "<input id='audio_path' type='hidden'>"
        "<div class='controls-row'><div class='volume-control'><input id='audio_vol' type='range' min='0' max='100' value='70' oninput=\"volInput(this.value)\"><span class='muted'>Volume: <span id='audio_vol_val'>70</span>%</span></div><div class='control-buttons'><button id='audio_repeat_btn' class='icon-btn icon-repeat' onclick='toggleRepeat()' title='Repeat track'></button><button id='audio_pause_btn' class='icon-btn icon-pause' onclick='togglePause()' title='Pause'></button><button id='audio_stop_btn' class='icon-btn icon-stop' onclick='stopPlay()' title='Stop'></button></div></div>"
        "<div class='progress-box'><div class='row progress-row'><input id='audio_prog' type='range' min='0' max='10000' value='0' step='1' oninput=\"scrubPreview(this.value)\" onchange=\"commitScrub(this.value)\" onmousedown=\"startScrub()\" onmouseup=\"finishScrub()\" ontouchstart=\"startScrub()\" ontouchend=\"finishScrub()\" ontouchcancel=\"finishScrub()\"><span class='muted'>Progress: <span id='audio_prog_txt'>0:00 / ?</span></span></div></div>"
        "<div id='audio_status' class='muted small'>Loading files...</div>"
        "<div class='file-browser'>"
        "<div class='audio-browser-toolbar'><div class='audio-nav-actions'><button onclick='navRoot()'>Root</button><button onclick='navUp()'>Back</button><button onclick='loadFiles()'>Refresh</button></div><div id='audio_breadcrumbs' class='audio-breadcrumbs'></div><div class='audio-search-wrap'><input id='audio_search' type='search' placeholder='Filter tracks in current folder' oninput=\"applyAudioTrackFilter(this.value)\"></div></div>"
        "<div class='audio-browser-grid'><div class='audio-browser-section'><div class='audio-section-head'><h4>Folders</h4><span id='audio_folders_meta' class='muted small'>0 folders</span></div><div id='audio_folders' class='folder-row'></div></div><div class='audio-browser-section'><div class='audio-section-head'><h4>Tracks</h4><span id='audio_tracks_meta' class='muted small'>0 tracks</span></div><div id='audio_files' class='file-grid audio-track-grid'></div></div></div>"
"</div>"
"</div></div>"
"<datalist id='track_lookup'></datalist>"

"<div class='pane' id='pane-settings'>"
"<div class='card'><h3>Settings</h3>"
"<div id='bootstrap_auth_card' class='card' style='display:none;'><h3>Set admin password</h3>"
"<div class='muted small'>First login uses the bootstrap password `admin`. Set a new admin password before using SceneHub.</div>"
"<div class='row'><input id='bootstrap_admin_user' placeholder='Username' readonly><input id='bootstrap_admin_new' type='password' placeholder='New admin password'><input id='bootstrap_admin_confirm' type='password' placeholder='Repeat new password'></div>"
"<button type='button' onclick='saveBootstrapPassword()'>Set admin password</button><button type='button' onclick='logout()'>Log out</button>"
"<div id='bootstrap_auth_status' class='muted small'></div>"
"</div>"
"<div class='card' data-force-change-hide='1'><h3>Settings</h3>"
        "<div class='row'><input id='ssid' placeholder='SSID'><input id='pass' placeholder='Password'><input id='host' placeholder='Hostname'></div>"
"<button type='button' onclick='saveWifi()'>Save Wi-Fi</button>"
"<button type='button' onclick='scanWifi()'>Scan</button>"
        "<div id='wifi_list' class='list'></div>"
        "<div class='muted'>If AP is up, use the setup AP password configured in firmware.</div>"
        "</div>"
"<div class='card' data-force-change-hide='1'><h3>MQTT</h3>"
"<div class='row'><input id='mqtt_id' placeholder='Broker ID'><input id='mqtt_port' placeholder='Port' style='max-width:140px'><input id='mqtt_keep' placeholder='Keepalive s' style='max-width:160px'></div>"
"<button type='button' onclick='saveMqtt()'>Save</button>"
"<div class='muted small'>MQTT users (client ID + username/password). Devices must use these credentials.</div>"
"<div id='mqtt_users_list' class='list'></div>"
"<div class='controls-row'><button type='button' onclick='addMqttUser()'>Add user</button><button type='button' onclick='saveMqttUsers()'>Save users</button></div>"
"</div>"
"<div class='card' data-force-change-hide='1'><h3>Web auth</h3>"
"<div class='muted small'>Administrator</div>"
"<div class='row'><input id='web_user' placeholder='Username'><input id='web_pass_current' type='password' placeholder='Current password'><input id='web_pass_new' type='password' placeholder='New password'></div>"
"<button type='button' onclick='saveWebPassword()'>Update admin credentials</button><button type='button' onclick='logout()'>Log out</button>"
"<div id='web_auth_status' class='muted small'></div>"
"<div class='muted small' style='margin-top:12px;'>Operator (read-only)</div>"
"<div class='row'><input id='op_user' placeholder='Operator username'><input id='op_pass' type='password' placeholder='Operator password'></div>"
"<input id='op_admin_current' type='password' placeholder='Admin password to confirm' style='margin-top:8px;'>"
"<button type='button' onclick='saveOperatorAccount()'>Save operator account</button>"
"<div id='op_auth_status' class='muted small'></div>"
"</div>"
"<div class='card' data-force-change-hide='1'><h3>Publish MQTT</h3>"
"<div class='row'><input id='pub_topic' placeholder='topic'><input id='pub_payload' placeholder='payload'></div>"
"<button type='button' onclick='publishMsg()'>Send</button>"
"</div>"
"<div class='card' data-force-change-hide='1'><h3>Diagnostics</h3>"
"<label class='muted small'><input type='checkbox' id='diag_verbose'> Enable verbose logs</label>"
"<div class='muted small'>Use for troubleshooting; turn off for normal play.</div>"
"<button type='button' onclick='saveDiagnostics()'>Apply</button>"
"</div>"
"</div>"
"<div class='pane' id='pane-devices'>"
"<div class='card'><h3>Devices moved</h3>"
"<div class='muted small'>Device monitoring and setup are now in the GM panel.</div>"
"<a class='gm-entry' href='/gm'>Open GM Panel</a>"
"</div>"
"</div>"
"<script>"
        "const MAX_PARALLEL_REQUESTS=2;"
"const __fetchQueue=[];"
"let __fetchActive=0;"
"const __origFetch=window.fetch.bind(window);"
"function __handleFetchResponse(res){if(res.status===401){const next=encodeURIComponent(window.location.pathname||'/');window.location='/login?next='+next;throw new Error('Unauthorized');}if(res.status===403){const ct=res.headers.get('content-type')||'';if(ct.includes('application/json')){res.clone().json().then(data=>{if(data&&data.error==='password_change_required'){window.location='/?force_password_change=1';}}).catch(()=>{});} }return res;}"
"function __runFetchQueue(){if(__fetchActive>=MAX_PARALLEL_REQUESTS)return;const job=__fetchQueue.shift();if(!job)return;__fetchActive++;__origFetch(...job.args).then(__handleFetchResponse).then(job.resolve,job.reject).finally(()=>{__fetchActive--;__runFetchQueue();});}"
"window.fetch=(...args)=>new Promise((resolve,reject)=>{__fetchQueue.push({args,resolve,reject});__runFetchQueue();});"
"window.__WEB_SESSION=null;"
        "const tabs=document.querySelectorAll('.tab');const panes=document.querySelectorAll('.pane');"
"const tabIconDefaults=['status','audio','devices','settings'];"
"tabs.forEach((tab,idx)=>{if(!tab.dataset.icon){tab.dataset.icon=tabIconDefaults[idx%tabIconDefaults.length];}});"
"const loadedTabs={status:true,audio:false};"
        "tabs.forEach(t=>t.onclick=()=>{tabs.forEach(x=>x.classList.remove('active'));panes.forEach(p=>p.classList.remove('active'));t.classList.add('active');document.getElementById('pane-'+t.dataset.tab).classList.add('active');ensureTabLoaded(t.dataset.tab);});"
"function activateTab(tabName){const target=document.querySelector(`.tab[data-tab='${tabName}']`);const pane=document.getElementById('pane-'+tabName);if(!target||!pane)return;tabs.forEach(x=>x.classList.remove('active'));panes.forEach(p=>p.classList.remove('active'));target.classList.add('active');pane.classList.add('active');ensureTabLoaded(tabName);}"
"function applyRoleLayout(role){const body=document.body;const session=window.__WEB_SESSION||{};const forceChange=!!session.password_change_required;if(body){body.dataset.role=role||'admin';body.dataset.passwordChangeRequired=forceChange?'1':'0';}if(document.body){document.body.classList.remove('role-user');}tabs.forEach(tab=>{tab.style.display='';if(forceChange&&role==='admin'&&tab.dataset.tab!=='settings'){tab.style.display='none';}});document.querySelectorAll('[data-force-change-hide=\"1\"]').forEach(el=>{el.style.display=(forceChange&&role==='admin')?'none':'';});const bootstrapCard=document.getElementById('bootstrap_auth_card');if(bootstrapCard){bootstrapCard.style.display=(forceChange&&role==='admin')?'block':'none';}const gmLink=document.querySelector('.gm-entry');if(gmLink){gmLink.style.display=(forceChange&&role==='admin')?'none':'';}if(forceChange&&role==='admin'){const bootstrapUser=document.getElementById('bootstrap_admin_user');if(bootstrapUser){bootstrapUser.value=session.username||'admin';}setTxt('banner','Default admin password is active. Change it before using SceneHub.');setTxt('status_state','Password change required.');setTxt('bootstrap_auth_status','Sign in succeeded, but bootstrap credentials are still active.');setTimeout(()=>{activateTab('settings');const nextField=document.getElementById('bootstrap_admin_new');if(nextField){nextField.focus();}},0);}}"
"function loadSessionRole(){return fetch('/api/session/info').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(info=>{window.__WEB_SESSION=info||{role:'admin',username:'',password_change_required:false};applyRoleLayout(window.__WEB_SESSION.role||'admin');return info;}).catch(()=>{window.__WEB_SESSION={role:'admin',username:'',password_change_required:false};applyRoleLayout('admin');return window.__WEB_SESSION;});}"
"const sessionRolePromise=loadSessionRole();"
"window.__sessionRolePromise=sessionRolePromise;"
"function ensureTabLoaded(tab){switch(tab){case 'audio':if(!loadedTabs.audio){loadFiles().then(()=>{loadedTabs.audio=true;}).catch(()=>{});}break;default:break;}}"
        "function ping(){fetch('/api/ping').then(r=>r.text()).then(alert);} "
        "let apPopupShown=false;"
"function updateBanner(j){const b=document.getElementById('banner');const badge=document.getElementById('status_badge');const ap=j.wifi.ap;const ip=j.wifi.sta_ip;const forceChange=!!(window.__WEB_SESSION&&window.__WEB_SESSION.password_change_required);badge.textContent=ap?'AP+STA':'STA';badge.style.background=ap?'#f97316':'#1f2430';if(forceChange){b.textContent='Initial admin password must be changed before normal use.';return;}if(ap){b.textContent='Setup mode: AP+STA, AP will be disabled after STA connects.';}else{b.textContent='Connected to '+j.wifi.ssid+' IP '+(ip||'none');}}"
"function setTxt(id,v){const el=document.getElementById(id);if(el){el.textContent=v;}}"
"function escapeHtml(text){if(text===undefined||text===null)return'';return String(text).replace(/[&<>\"']/g,c=>({\"&\":\"&amp;\",\"<\":\"&lt;\",\">\":\"&gt;\",\"\\\"\":\"&quot;\",\"'\":\"&#39;\"}[c]||c));}"
        "function renderDots(id,count,max){const el=document.getElementById(id);if(!el)return;el.innerHTML='';for(let i=0;i<max;i++){const dot=document.createElement('span');dot.style.background=i<count?'#22c55e':'#1f2937';el.appendChild(dot);}}"
"function humanMb(bytes){if(!bytes||bytes<=0)return'-';return (bytes/1024/1024).toFixed(1)+' MB';}"
"function humanGb(bytes){if(!bytes||bytes<=0)return'0 GB';return (bytes/(1024*1024*1024)).toFixed(2)+' GB';}"
"function formatBytes(bytes){const value=Number(bytes||0);if(!value)return'0 B';const units=['B','KB','MB','GB'];let idx=0;let size=value;while(size>=1024&&idx<units.length-1){size/=1024;idx++;}return (idx===0?Math.round(size):size.toFixed(1))+' '+units[idx];}"
"let mqttUsers=[];"
"function otaPhaseLabel(phase){switch(phase){case 'uploading':return 'Uploading';case 'reboot_required':return 'Reboot required';case 'rebooting':return 'Rebooting';case 'verify_wait_ready':return 'Waiting for system ready';case 'verify_pending':return 'Pending confirm';case 'idle':default:return 'Idle';}}"
"function otaPhaseHint(phase){switch(phase){case 'uploading':return 'Firmware transfer is in progress. Wait until the image is fully written.';case 'reboot_required':return 'Firmware image is installed. Review status and press Reboot now when ready.';case 'rebooting':return 'Reboot has been requested. Wait for the board to restart and reconnect.';case 'verify_wait_ready':return 'New image has booted. Waiting for the application to report healthy startup.';case 'verify_pending':return 'Rollback-capable image is awaiting confirmation. The device should confirm automatically after healthy startup.';case 'idle':default:return 'Idle. You can upload a new firmware image.';}}"
"function renderOtaStatus(ota){const data=ota||{};const phase=data.phase||'idle';setTxt('ota_version',data.version||'n/a');setTxt('ota_running',data.running_partition||'n/a');setTxt('ota_boot',data.boot_partition||'n/a');const states=[otaPhaseLabel(phase)];if(!data.rollback_supported){states.push('No rollback');}setTxt('ota_state',states.join(' · '));setTxt('ota_phase_hint',otaPhaseHint(phase));const rebootBtn=document.getElementById('ota_reboot_btn');if(rebootBtn){rebootBtn.disabled=phase!=='reboot_required';}const uploadBtn=document.getElementById('ota_upload_btn');if(uploadBtn){uploadBtn.disabled=phase==='uploading'||phase==='rebooting';}const fileInput=document.getElementById('ota_file');if(fileInput){fileInput.disabled=phase==='uploading'||phase==='rebooting';}const details=document.getElementById('ota_last_error');if(details){const progress=phase==='uploading'&&data.total_bytes?` Upload ${formatBytes(data.bytes_written||0)} / ${formatBytes(data.total_bytes||0)}.`:'';const message=(data.last_error&&data.last_error.length)?data.last_error:'No OTA errors.';details.textContent=message+progress;details.style.color=(data.last_error&&data.last_error.length)?'#fca5a5':'#94a3b8';}}"
"function serviceBadge(name,svc){if(!svc||!svc.init_attempted)return `${name}:n/a`;if(!svc.init_ok)return `${name}:init-fail`;if(svc.start_attempted&&!svc.start_ok)return `${name}:start-fail`;if(svc.start_attempted&&svc.start_ok)return `${name}:ok`;return `${name}:init-only`;}"
"function renderStatus(j){window.__SCENEHUB_STATUS=j||{};setTxt('status_raw',JSON.stringify(j,null,2));setTxt('status_ssid',j.wifi.ssid||'n/a');setTxt('status_ip',j.wifi.sta_ip||'none');const sd=j.sd||{};if(sd.ok){setTxt('status_sd_size',`${humanGb(sd.total)} / free ${humanGb(sd.free)}`);}else{setTxt('status_sd_size','No card');}const mem=j.mem||{};const dram=mem.dram||{};const psram=mem.psram||{};setTxt('status_ram',dram.total_kb?`${dram.free_kb||0} / ${dram.total_kb} KB`:'n/a');setTxt('status_psram',psram.total_kb?`${psram.free_kb||0} / ${psram.total_kb} KB`:'n/a');setTxt('status_clients',j.clients?j.clients.total:0);const services=j.services||{};setTxt('status_services',[serviceBadge('net',services.network),serviceBadge('mqtt',services.mqtt),serviceBadge('audio',services.audio),serviceBadge('ui',services.web_ui)].join(' | '));const webUserInput=document.getElementById('web_user');if(webUserInput){webUserInput.value=(j.web&&j.web.username)||'';}const operatorUser=document.getElementById('op_user');if(operatorUser){operatorUser.value=(j.web&&j.web.operator&&j.web.operator.username)||'';}const diagBox=document.getElementById('diag_verbose');if(diagBox){diagBox.checked=!!(j.diag&&j.diag.verbose_logging);}if(window.__WEB_SESSION&&j.web){window.__WEB_SESSION.password_change_required=!j.web.password_initialized;}renderOtaStatus(j.ota||{});}"
"function renderMqttUsers(list){mqttUsers=Array.isArray(list)?list.map(u=>({client_id:u&&u.client_id?u.client_id:'',username:u&&u.username?u.username:'',password:'',password_set:!!(u&&u.password_set)})):[];const wrap=document.getElementById('mqtt_users_list');if(!wrap)return;if(!mqttUsers.length){wrap.innerHTML=\"<div class='muted small'>No users configured.</div>\";return;}wrap.innerHTML=mqttUsers.map((user,idx)=>`<div class=\"mqtt-user-row\"><input placeholder=\"Client ID\" value=\"${escapeHtml(user.client_id)}\" oninput=\"updateMqttUser(${idx},'client_id',this.value)\"><input placeholder=\"Username\" value=\"${escapeHtml(user.username)}\" oninput=\"updateMqttUser(${idx},'username',this.value)\"><input type=\"password\" placeholder=\"${user.password_set?'Leave blank to keep existing password':'Password'}\" value=\"${escapeHtml(user.password)}\" oninput=\"updateMqttUser(${idx},'password',this.value)\"><button type=\"button\" onclick=\"removeMqttUser(${idx})\">Remove</button></div>`).join('');}"
"function addMqttUser(){mqttUsers.push({client_id:'',username:'',password:''});renderMqttUsers(mqttUsers);}"
"function updateMqttUser(idx,field,value){if(!mqttUsers[idx])return;mqttUsers[idx][field]=value;}"
"function removeMqttUser(idx){if(idx<0||idx>=mqttUsers.length)return;mqttUsers.splice(idx,1);renderMqttUsers(mqttUsers);}"
"function saveMqttUsers(){const sanitized=mqttUsers.map(u=>({client_id:(u.client_id||'').trim(),username:(u.username||'').trim(),password:(u.password||'').trim()})).filter(u=>u.client_id&&u.username);fetch('/api/config/mqtt_users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(sanitized)}).then(r=>r.text()).then(alert).then(()=>loadStatus());}"
"let rawShown=false;"
"function toggleRaw(){rawShown=!rawShown;const pre=document.getElementById('status_raw');const btn=document.getElementById('status_raw_btn');if(pre){pre.style.display=rawShown?'block':'none';}if(btn){btn.textContent=rawShown?'Hide raw':'Show raw';}}"
"function refreshOtaStatus(){const status=document.getElementById('ota_upload_status');if(status){status.textContent='Refreshing OTA status...';}return fetch('/api/ota/status').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(j=>{renderOtaStatus(j||{});if(status){status.textContent='OTA status updated.';}}).catch(err=>{if(status){status.textContent=err.message||'Failed to refresh OTA status.';}throw err;});}"
"function uploadFirmware(){const input=document.getElementById('ota_file');const status=document.getElementById('ota_upload_status');const file=input&&input.files&&input.files[0];if(!status){return;}if(!file){status.textContent='Select a firmware .bin file.';return;}status.textContent=`Uploading ${file.name} (${formatBytes(file.size)})...`;fetch('/api/ota/upload',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Firmware-Name':file.name||'firmware.bin'},body:file}).then(async res=>{const text=await res.text().catch(()=>''),clean=(text||'').trim();if(!res.ok){throw new Error(clean||'OTA upload failed.');}let payload=null;try{payload=clean?JSON.parse(clean):null;}catch(_){payload=null;}status.textContent=payload&&payload.phase==='reboot_required'?'Firmware uploaded. Reboot required.':'Firmware uploaded.';setTimeout(()=>{refreshOtaStatus().catch(()=>{});loadStatus().catch(()=>{});},1000);}).catch(err=>{status.textContent=err.message||'OTA upload failed.';});}"
"function requestOtaReboot(){const status=document.getElementById('ota_upload_status');if(status){status.textContent='Requesting reboot...';}fetch('/api/ota/reboot',{method:'POST'}).then(async res=>{const text=await res.text().catch(()=>''),clean=(text||'').trim();if(!res.ok){throw new Error(clean||'Reboot request failed.');}if(status){status.textContent='Reboot requested. Device is restarting...';}setTimeout(()=>{refreshOtaStatus().catch(()=>{});loadStatus().catch(()=>{});},8000);}).catch(err=>{if(status){status.textContent=err.message||'Reboot request failed.';}});}"
"function loadStatus(){setTxt('status_state','Loading...');return fetch('/api/status').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(j=>{renderStatus(j);setTxt('status_state','Updated');document.getElementById('ssid').value=j.wifi.ssid;document.getElementById('host').value=j.wifi.host;document.getElementById('mqtt_id').value=j.mqtt.id;document.getElementById('mqtt_port').value=j.mqtt.port;document.getElementById('mqtt_keep').value=j.mqtt.keepalive;renderMqttUsers((j.mqtt&&j.mqtt.users)||[]);updateAudioFromStatus(j.audio||{});updateBanner(j);if(j.wifi.sta_ip&&j.wifi.sta_ip.length>0&&j.wifi.ap&&!apPopupShown){apPopupShown=true;setTxt('status_state','Connected. AP shutdown is handled by network service.');}}).catch(err=>{setTxt('status_state','Failed to load');setTxt('status_raw',err.message);});}"
        "function saveWifi(){const payload={ssid:ssid.value,host:host.value};if(pass.value)payload.password=pass.value;fetch('/api/config/wifi',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.text()).then(alert);}"
        "function scanWifi(){fetch('/api/wifi/scan').then(r=>r.json()).then(list=>{const c=document.getElementById('wifi_list');c.innerHTML='';list.forEach(name=>{const d=document.createElement('div');d.className='pill';d.textContent=name;d.onclick=()=>{ssid.value=name;};c.appendChild(d);});});}"
"function saveMqtt(){const payload={id:mqtt_id.value,port:Number(mqtt_port.value||0),keepalive:Number(mqtt_keep.value||0)};fetch('/api/config/mqtt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.text()).then(alert);}"
"function saveBootstrapPassword(){const user=(document.getElementById('bootstrap_admin_user').value||'').trim()||'admin';const next=document.getElementById('bootstrap_admin_new').value;const confirm=document.getElementById('bootstrap_admin_confirm').value;const status=document.getElementById('bootstrap_auth_status');if(!next){status.textContent='Enter a new admin password.';return;}if(next!==confirm){status.textContent='Passwords do not match.';return;}status.textContent='Saving...';fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:'admin',username:user,new_password:next})}).then(async res=>{if(!res.ok){throw new Error((await res.text().catch(()=>''))||'Failed to save.');}status.textContent='Password updated. Please log in again.';document.getElementById('bootstrap_admin_new').value='';document.getElementById('bootstrap_admin_confirm').value='';setTimeout(()=>{window.location='/login';},800);}).catch(err=>{status.textContent=err.message||'Failed';});}"
"function saveWebPassword(){const user=(document.getElementById('web_user').value||'').trim();const current=document.getElementById('web_pass_current').value;const next=document.getElementById('web_pass_new').value;const status=document.getElementById('web_auth_status');if(!current||!next){status.textContent='Fill current and new password.';return;}status.textContent='Saving...';fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:'admin',username:user,current_password:current,new_password:next})}).then(async res=>{if(res.status===403){throw new Error('Current password is invalid.');}if(!res.ok){throw new Error((await res.text().catch(()=>''))||'Failed to save.');}status.textContent='Updated. Please log in again.';document.getElementById('web_pass_current').value='';document.getElementById('web_pass_new').value='';setTimeout(()=>{window.location='/login';},800);}).catch(err=>{status.textContent=err.message||'Failed';});}"
"function saveOperatorAccount(){const username=(document.getElementById('op_user').value||'').trim();const password=document.getElementById('op_pass').value;const adminCurrent=document.getElementById('op_admin_current').value;const status=document.getElementById('op_auth_status');if(!adminCurrent){status.textContent='Enter admin password.';return;}if(!username||!password){status.textContent='Operator username/password required.';return;}status.textContent='Saving...';const payload={role:'user',username:username,current_password:adminCurrent,new_password:password};fetch('/api/auth/password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(async res=>{if(res.status===403){throw new Error('Admin password invalid.');}if(!res.ok){throw new Error((await res.text().catch(()=>''))||'Failed to save.');}status.textContent='Operator account updated.';document.getElementById('op_pass').value='';document.getElementById('op_admin_current').value='';}).catch(err=>{status.textContent=err.message||'Failed';});}"
"function logout(){fetch('/api/auth/logout',{method:'POST'}).finally(()=>{window.location='/login';});}"
"const PROGRESS_MAX=10000;"
"const TRACK_LIST_ID='track_lookup';"
"function updateTrackLookupOptions(files){const list=document.getElementById(TRACK_LIST_ID);if(!list){return;}list.innerHTML='';if(!Array.isArray(files)||!files.length){return;}const groups={};files.forEach(entry=>{if(!entry||!entry.path)return;const dir=audioDirName(entry.path);if(!groups[dir]){groups[dir]=[];}groups[dir].push(entry.path);});Object.keys(groups).sort((a,b)=>a.localeCompare(b)).forEach(dir=>{const header=document.createElement('option');header.value='';header.disabled=true;header.textContent=dir||'/';list.appendChild(header);groups[dir].sort((a,b)=>audioBaseName(a).localeCompare(audioBaseName(b))).forEach(path=>{const opt=document.createElement('option');opt.value=path;opt.textContent=audioBaseName(path);opt.label=`${dir||'/'} / ${audioBaseName(path)}`;list.appendChild(opt);});});}"
"const SEEK_DEBOUNCE_MS=150;"
"const SEEK_ACK_THRESHOLD=50;"
"const SEEK_MAX_HOLD_MS=2000;"
        "let audioPlaying=false;"
        "let audioPaused=false;"
        "let currentPlayingPath='';"
        "let lastPlayedPath='';"
        "let pendingTrackPath='';"
        "let repeatOne=false;"
        "let repeatInFlight=false;"
        "let progressScrubbing=false;"
"let seekTimer=null;"
"let seekQueuedValue=null;"
"let seekPending=false;"
"let seekReleaseTimer=null;"
"let seekLastTargetMs=null;"
        "function refreshModeButtons(){}"
        "function play(path){const p=path||audio_path.value; if(!p){alert('Select a track');return;}"
        " setFileStatus('Playing...',false);"
        " resetProgressUI(true);"
        " pendingTrackPath=p;"
        " lastPlayedPath=p;"
        " repeatInFlight=false;"
        " const start=()=>fetch(`/api/audio/play?path=${encodeURIComponent(p)}&volume=${audio_vol.value}`,{method:'POST'}).then(r=>r.text()).then(()=>{audioPlaying=true;audioPaused=false;currentPlayingPath=p;setFileStatus('Playing',false);markPlayingCard();}).catch(()=>setFileStatus('Play failed',true));"
        " if(currentPlayingPath){fetch('/api/audio/stop',{method:'POST'}).catch(()=>{}).finally(()=>{start();});}else{start();}"
        "}"
        "function pauseAudio(){fetch('/api/audio/pause',{method:'POST'}).then(()=>{audioPaused=true;setFileStatus('Paused',false);updatePauseBtn();}).catch(()=>setFileStatus('Pause failed',true));}"
        "function resumeAudio(){fetch('/api/audio/resume',{method:'POST'}).then(()=>{audioPaused=false;setFileStatus('Playing',false);updatePauseBtn();}).catch(()=>setFileStatus('Resume failed',true));}"
        "function togglePause(){if(audioPaused){resumeAudio();}else{pauseAudio();}}"
        "function updatePauseBtn(){const btn=document.getElementById('audio_pause_btn');if(!btn)return;btn.title=audioPaused?'Resume':'Pause';if(audioPaused){btn.classList.add('icon-play');btn.classList.remove('icon-pause');}else{btn.classList.add('icon-pause');btn.classList.remove('icon-play');}}"
        "function stopPlay(){fetch('/api/audio/stop',{method:'POST'}).then(()=>{audioPlaying=false;audioPaused=false;currentPlayingPath='';lastPlayedPath='';pendingTrackPath='';repeatInFlight=false;markPlayingCard();setFileStatus('Stopped',false);resetProgressUI(true);updatePauseBtn();}).catch(()=>setFileStatus('Stop failed',true));}"
"function setVolume(v){volInput(v,true);}"
"function publishMsg(){fetch(`/api/publish?topic=${encodeURIComponent(pub_topic.value)}&payload=${encodeURIComponent(pub_payload.value)}`,{method:'POST'}).then(r=>r.text());}"
"function saveDiagnostics(){const box=document.getElementById('diag_verbose');if(!box){return;}fetch('/api/config/logging',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({verbose:!!box.checked})}).then(r=>r.text()).then(alert).then(()=>loadStatus()).catch(()=>{});}"
"const AUDIO_ROOT='" SD_STORAGE_ROOT_PATH "';"
"const AUDIO_ROOT_LEN=AUDIO_ROOT.length;"
"let audioCurrentDir=AUDIO_ROOT;"
"let audioCurrentFolders=[];"
"let audioCurrentFiles=[];"
"let audioFilterQuery='';"
"let audioVolumeTimer=null;"
"let audioDurationMs=0;"
"let audioPosMs=0;"
"function setFileStatus(msg,isError){const el=document.getElementById('audio_status');if(!el)return;el.textContent=msg||'';el.style.color=isError?'#f87171':'#94a3b8';}"
"function audioBaseName(path){if(!path)return'';const parts=path.split('/').filter(Boolean);return parts.length?parts[parts.length-1]:path;}"
"function audioDirName(path){if(!path)return'/';const idx=path.lastIndexOf('/');if(idx<0)return'/';const dir=path.slice(0,idx)||'/';return dir||'/';}"
"function audioExtName(path){const base=audioBaseName(path);const idx=base.lastIndexOf('.');return idx>0?base.slice(idx+1).toUpperCase():'TRACK';}"
"function audioDisplayRootName(){const trimmed=(AUDIO_ROOT||'').replace(/^\\/+|\\/+$/g,'');if(!trimmed)return'/';const parts=trimmed.split('/').filter(Boolean);return parts.length?parts[parts.length-1]:AUDIO_ROOT;}"
"function audioCountLabel(count,singular,plural){return count+' '+(count===1?singular:plural);}"
"function renderAudioBreadcrumbs(path){const wrap=document.getElementById('audio_breadcrumbs');if(!wrap)return;wrap.innerHTML='';const current=path||AUDIO_ROOT;const root=document.createElement('button');root.type='button';root.className='audio-breadcrumb'+(current===AUDIO_ROOT?' active':'');root.textContent=audioDisplayRootName();root.onclick=()=>navRoot();wrap.appendChild(root);const suffix=current.startsWith(AUDIO_ROOT)?current.slice(AUDIO_ROOT.length):'';const segments=suffix.split('/').filter(Boolean);let acc=AUDIO_ROOT;segments.forEach((segment,idx)=>{const sep=document.createElement('span');sep.className='audio-breadcrumb-sep';sep.textContent='/';wrap.appendChild(sep);acc+='/'+segment;const crumb=document.createElement('button');crumb.type='button';crumb.className='audio-breadcrumb'+(idx===segments.length-1?' active':'');crumb.textContent=segment;const target=acc;crumb.onclick=()=>loadFiles(target);wrap.appendChild(crumb);});}"
"function renderAudioFolders(){const folders=audioCurrentFolders.slice().sort((a,b)=>audioBaseName(a.path).localeCompare(audioBaseName(b.path)));const folderWrap=document.getElementById('audio_folders');if(folderWrap){folderWrap.innerHTML='';if(!folders.length){const empty=document.createElement('div');empty.className='audio-empty';empty.textContent='No folders in this location';folderWrap.appendChild(empty);}else{const frag=document.createDocumentFragment();folders.forEach(entry=>{const chip=document.createElement('div');chip.className='folder-chip';chip.textContent=audioBaseName(entry.path);chip.onclick=()=>loadFiles(entry.path);frag.appendChild(chip);});folderWrap.appendChild(frag);folderWrap.scrollTop=0;}}const foldersMeta=document.getElementById('audio_folders_meta');if(foldersMeta){foldersMeta.textContent=audioCountLabel(folders.length,'folder','folders');}}"
"function renderAudioFiles(){const files=audioCurrentFiles.slice().sort((a,b)=>audioBaseName(a.path).localeCompare(audioBaseName(b.path)));const filter=audioFilterQuery;const visibleFiles=filter?files.filter(entry=>audioBaseName(entry.path).toLowerCase().includes(filter)):files;const selectedInput=document.getElementById('audio_path');const selectedPath=selectedInput?selectedInput.value:'';const fileWrap=document.getElementById('audio_files');if(fileWrap){fileWrap.innerHTML='';if(!visibleFiles.length){const empty=document.createElement('div');empty.className='audio-empty';empty.textContent=files.length?'No tracks match this filter':'No tracks in current folder';fileWrap.appendChild(empty);}else{const frag=document.createDocumentFragment();visibleFiles.forEach(entry=>{const card=document.createElement('div');card.className='track-card';card.dataset.path=entry.path;if(selectedPath&&selectedPath===entry.path){card.classList.add('selected');}const label=document.createElement('div');label.className='track-name';label.textContent=audioBaseName(entry.path);const meta=document.createElement('div');meta.className='track-meta';meta.textContent=audioExtName(entry.path);card.appendChild(label);card.appendChild(meta);card.onclick=()=>selectTrack(entry.path,card);frag.appendChild(card);});fileWrap.appendChild(frag);}}const tracksMeta=document.getElementById('audio_tracks_meta');if(tracksMeta){tracksMeta.textContent=filter?`${audioCountLabel(visibleFiles.length,'track','tracks')} shown of ${files.length}`:audioCountLabel(files.length,'track','tracks');}updateTrackLookupOptions(files);markPlayingCard();}"
"function renderAudioListing(list){if(Array.isArray(list)){audioCurrentFolders=list.filter(item=>item&&item.dir);audioCurrentFiles=list.filter(item=>item&&!item.dir);}renderAudioBreadcrumbs(audioCurrentDir);renderAudioFolders();renderAudioFiles();}"
"function applyAudioTrackFilter(value){audioFilterQuery=(value||'').trim().toLowerCase();renderAudioFiles();}"
"function selectTrack(path,card){const input=document.getElementById('audio_path');if(input){input.value=path||'';}document.querySelectorAll('#audio_files .track-card.selected').forEach(el=>el.classList.remove('selected'));if(card){card.classList.add('selected');}const shouldAutoPlay=!!(path&&(!audioPlaying||path!==currentPlayingPath));setFileStatus(path?('Selected '+audioBaseName(path)):'No track',false);if(shouldAutoPlay){play(path);}}"
"function markPlayingCard(){const cards=document.querySelectorAll('#audio_files .track-card');cards.forEach(card=>{if(card.dataset.path===currentPlayingPath){card.classList.add('playing');}else{card.classList.remove('playing');}});}"
"function loadFiles(path){const target=path||audioCurrentDir||AUDIO_ROOT;setFileStatus('Loading...',false);const url='/api/files?path='+encodeURIComponent(target);return fetch(url).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(list=>{audioCurrentDir=target;renderAudioListing(list);setFileStatus('Loaded',false);return list;}).catch(err=>{setFileStatus(err.message||'Load failed',true);throw err;});}"
"function navRoot(){if(audioCurrentDir===AUDIO_ROOT){renderAudioBreadcrumbs(AUDIO_ROOT);return;}loadFiles(AUDIO_ROOT);}"
"function navUp(){if(!audioCurrentDir||audioCurrentDir===AUDIO_ROOT){return;}const idx=audioCurrentDir.lastIndexOf('/');const next=idx>AUDIO_ROOT_LEN?audioCurrentDir.slice(0,idx):AUDIO_ROOT;loadFiles(next);}"
"function formatMs(ms){if(!ms||ms<=0)return'0:00';const total=Math.floor(ms/1000);const m=Math.floor(total/60);const s=total%60;return m+':' + (s<10?'0'+s:s);}"
"function updateProgressDisplay(posMs,durMs){const slider=document.getElementById('audio_prog');const text=document.getElementById('audio_prog_txt');const pos=typeof posMs==='number'?posMs:audioPosMs;const dur=typeof durMs==='number'?durMs:audioDurationMs;if(slider&&!progressScrubbing){const ratio=dur>0?Math.max(0,Math.min(1,pos/(dur||1))):0;slider.value=Math.floor(ratio*PROGRESS_MAX);}if(text){const durText=dur>0?formatMs(dur):'?';text.textContent=formatMs(pos)+' / '+durText;}}"
"function resetProgressUI(clear){if(clear){audioDurationMs=0;}audioPosMs=0;updateProgressDisplay(0,clear?0:audioDurationMs);}"
"function updateAudioFromStatus(stat){if(!stat)return;audioPlaying=!!stat.playing;audioPaused=!!stat.paused;audioDurationMs=stat.dur_ms||0;audioPosMs=stat.pos_ms||0;if(typeof stat.volume==='number'){const slider=document.getElementById('audio_vol');if(slider){slider.value=stat.volume;}volInput(stat.volume,true);}if(stat.path){currentPlayingPath=stat.path;lastPlayedPath=stat.path;}else if(!audioPlaying&&!audioPaused){currentPlayingPath='';}setFileStatus(stat.message||(audioPlaying?'Playing':'Idle'),false);updateProgressDisplay();markPlayingCard();updatePauseBtn();}"
"function volInput(val,fromStatus){const display=document.getElementById('audio_vol_val');if(display){display.textContent=val;}if(fromStatus){return;}if(audioVolumeTimer){clearTimeout(audioVolumeTimer);}audioVolumeTimer=setTimeout(()=>{fetch('/api/audio/volume?val='+encodeURIComponent(val),{method:'POST'}).catch(()=>{});},200);}"
"function scrubPreview(value){const raw=parseInt(value,10)||0;const ratio=Math.max(0,Math.min(1,raw/PROGRESS_MAX));const preview=Math.floor(ratio*(audioDurationMs||0));const text=document.getElementById('audio_prog_txt');if(text){const dur=audioDurationMs>0?formatMs(audioDurationMs):'?';text.textContent=formatMs(preview)+' / '+dur;}scheduleSeek(raw);}"
"function scheduleSeek(value){if(!audioDurationMs)return;const next=typeof value==='number'?value:parseInt(value,10);if(Number.isNaN(next))return;seekQueuedValue=next;if(seekTimer){clearTimeout(seekTimer);}seekTimer=setTimeout(()=>commitScrub(),SEEK_DEBOUNCE_MS);if(seekReleaseTimer){clearTimeout(seekReleaseTimer);}seekReleaseTimer=setTimeout(()=>commitScrub(),SEEK_MAX_HOLD_MS);}"
"function commitScrub(value){const raw=(typeof value!=='undefined'&&value!==null)?value:seekQueuedValue;const sliderVal=typeof raw==='number'?raw:parseInt(raw,10);if(seekTimer){clearTimeout(seekTimer);seekTimer=null;}if(seekReleaseTimer){clearTimeout(seekReleaseTimer);seekReleaseTimer=null;}if(!audioDurationMs||sliderVal===null||Number.isNaN(sliderVal))return;seekQueuedValue=sliderVal;if(seekPending)return;const ratio=Math.max(0,Math.min(1,sliderVal/PROGRESS_MAX));const target=Math.floor(ratio*audioDurationMs);if(seekLastTargetMs!==null&&Math.abs(target-seekLastTargetMs)<SEEK_ACK_THRESHOLD){seekQueuedValue=null;return;}seekQueuedValue=null;seekPending=true;fetch(`/api/audio/seek?pos=${target}`,{method:'POST'}).then(()=>{audioPosMs=target;updateProgressDisplay();seekLastTargetMs=target;}).catch(()=>{setFileStatus('Seek failed',true);seekLastTargetMs=null;}).finally(()=>{seekPending=false;if(seekQueuedValue!==null){commitScrub();}});}"
"function startScrub(){progressScrubbing=true;}"
"function finishScrub(){progressScrubbing=false;updateProgressDisplay();commitScrub();}"
        "let statusInterval=null;"
        "function fetchAudioStatus(){return fetch('/api/status').then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}).then(j=>{if(j.audio){updateAudioFromStatus(j.audio);}}).catch(()=>{});}"
        "function toggleRepeat(){repeatOne=!repeatOne;const btn=document.getElementById('audio_repeat_btn');if(btn){if(repeatOne){btn.classList.add('active');}else{btn.classList.remove('active');}}}"
        "refreshModeButtons();"
"sessionRolePromise.then(info=>{if(info&&info.role==='user'){return;}loadStatus().then(()=>{if(info&&info.password_change_required){return;}if(statusInterval)clearInterval(statusInterval);statusInterval=setInterval(()=>{const activePane=document.querySelector('.pane.active');if(!activePane)return;const activeId=activePane.id;if(activeId==='pane-audio'){fetchAudioStatus();return;}if(activeId==='pane-status'){loadStatus().catch(()=>{});}},3000);});});"
"</script>"
        "</div>"
        "</body></html>";

static const char s_web_ui_login[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><title>SceneHub Login</title>"
"<style>"
"body{margin:0;padding:0;font-family:'Segoe UI',Tahoma,sans-serif;background:radial-gradient(circle at top,#12141a 0%,#0b0c10 26%,#08090b 64%,#07080a 100%);color:#eef2f6;display:flex;align-items:center;justify-content:center;height:100vh;}"
".card{background:linear-gradient(180deg,#171b21,#12151a);border:1px solid #2a3038;border-radius:8px;padding:28px;width:90%;max-width:360px;box-shadow:0 18px 40px rgba(0,0,0,.34);}"
".card h2{margin:0 0 18px;font-weight:700;text-align:center;}"
".card label{display:block;font-size:13px;color:#8d99a6;margin-top:12px;margin-bottom:4px;}"
".card input,.card select{width:100%;padding:10px 12px;border-radius:6px;border:1px solid #2a3038;background:#0f1217;color:#eef2f6;box-shadow:inset 0 1px 0 rgba(255,255,255,.02);}"
".card input:focus,.card select:focus{outline:none;border-color:rgba(240,180,58,.5);box-shadow:0 0 0 3px rgba(240,180,58,.08);}"
".card button{width:100%;margin-top:18px;background:linear-gradient(180deg,#222730,#171b21);color:#eef2f6;border:1px solid #2a3038;border-radius:6px;padding:12px;font-weight:700;cursor:pointer;box-shadow:0 10px 24px rgba(0,0,0,.24);}"
".card button:hover{background:linear-gradient(180deg,#272d37,#1a1f26);border-color:rgba(240,180,58,.4);}"
".muted{color:#8d99a6;font-size:13px;margin-top:12px;text-align:center;}"
".error{color:#f97316;font-size:13px;margin-top:8px;text-align:center;min-height:18px;}"
"</style></head><body>"
"<div class='card'><h2>SceneHub Login</h2>"
"<form id='login_form'>"
"<label for='login_user'>Username</label><input id='login_user' autocomplete='username' required>"
"<label for='login_pass'>Password</label><input id='login_pass' type='password' autocomplete='current-password' required>"
"<button type='submit'>Sign in</button>"
"<div id='login_status' class='error'></div>"
"<div class='muted'>Default first login is <strong>admin / admin</strong>. You will be forced to change it before normal use.</div>"
"<div class='muted'>Hold the reset pin during boot for setup AP, or hold it for 15 seconds after boot to restore defaults.</div>"
"</form></div>"
"<script>"
"const form=document.getElementById('login_form');"
"form.addEventListener('submit',async ev=>{ev.preventDefault();const username=document.getElementById('login_user').value.trim();const password=document.getElementById('login_pass').value;const status=document.getElementById('login_status');status.textContent='';try{const res=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});if(res.ok){let data=null;const contentType=res.headers.get('content-type')||'';if(contentType.includes('application/json')){data=await res.json().catch(()=>null);}if(data&&data.password_change_required){window.location='/?force_password_change=1';return;}const role=(data&&data.role)||'admin';const next=(new URLSearchParams(window.location.search).get('next')||'').trim();const nextIsBootstrap=next==='/'||next==='/login'||next.startsWith('/?force_password_change=1');if(role==='admin'){if(next&&!nextIsBootstrap){window.location=next;return;}window.location='/gm';return;}if(next&&next!=='/login'){window.location=next;return;}window.location='/';return;}let message='Login failed.';const contentType=res.headers.get('content-type')||'';if(contentType.includes('application/json')){const data=await res.json().catch(()=>null);if(data&&typeof data.message==='string'&&data.message){message=data.message;}}else{const text=await res.text().catch(()=>''),clean=(text||'').trim();if(clean){message=clean;}}status.textContent=message;}catch(err){status.textContent='Connection to SceneHub lost. The device may be offline or restarting.';}});"
"</script></body></html>";

const char *web_ui_get_index_html(void)
{
    return s_web_ui_index;
}

static const char s_web_ui_gm[] =
"<!DOCTYPE html><html><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>SceneHub GM</title>"
"<link rel='stylesheet' href='/ui/gm_panel.css?v=22'></head><body>"
"<div class='app'><aside class='sidebar'><div class='brand'><h1>GM Panel</h1><p>Quest control</p></div><nav class='nav' id='gm_nav'>"
"<button class='nav-btn active' data-view='rooms'><span class='nav-dot'></span>Rooms</button>"
"<button class='nav-btn' data-view='timeline'><span class='nav-dot'></span>Timeline</button>"
"<button class='nav-btn' data-view='audit'><span class='nav-dot'></span>Audit</button>"
"<div class='nav-divider admin-only'></div>"
"<button class='nav-btn admin-only' data-view='devices'><span class='nav-dot'></span>Device Controls</button>"
"<button class='nav-btn admin-only' data-view='profiles'><span class='nav-dot'></span>Game Modes</button>"
"<button class='nav-btn admin-only' data-view='scenarios'><span class='nav-dot'></span>Scenarios</button>"
"<button class='nav-btn admin-only' data-view='device_setup'><span class='nav-dot'></span>Device Setup</button>"
"<button class='nav-btn admin-only' data-view='hardware_io'><span class='nav-dot'></span>Hardware IO</button>"
"<button class='nav-btn admin-only' data-view='observed'><span class='nav-dot'></span>Observed</button>"
"<button class='nav-btn admin-only' data-view='storage'><span class='nav-dot'></span>Storage</button>"
"</nav></aside><main class='main'><header class='topbar'><div><div id='page_title' class='page-title'>Rooms</div><div id='page_sub' class='page-sub'>Loading state</div></div><div class='top-actions'><span id='gm_role_badge' class='role-badge'>role</span><span id='system_status' class='status state-unknown'>unknown</span><a id='gm_admin_home' class='top-link admin-only' href='/'>Admin</a><button id='gm_refresh'>Refresh</button><button id='gm_logout'>Logout</button></div></header><section id='gm_content' class='content'></section></main><aside class='right-sidebar' id='gm_right_sidebar'><div class='manual-empty'>Loading buttons...</div></aside></div>"
"<script src='/ui/gm_panel.js?v=68'></script></body></html>";

const char *web_ui_get_gm_html(void)
{
    return s_web_ui_gm;
}

const char *web_ui_get_login_html(void)
{
    return s_web_ui_login;
}
