#pragma once

#include "cJSON.h"
#include "esp_err.h"
#include "esp_http_server.h"
#include "scenehub_state.h"

esp_err_t web_ui_system_init(void);
esp_err_t meta_handler(httpd_req_t *req);
cJSON *web_ui_build_meta_json(void);
esp_err_t status_handler(httpd_req_t *req);
esp_err_t ota_status_handler(httpd_req_t *req);
esp_err_t ota_upload_handler(httpd_req_t *req);
esp_err_t ota_reboot_handler(httpd_req_t *req);
esp_err_t files_handler(httpd_req_t *req);
esp_err_t audio_play_handler(httpd_req_t *req);
esp_err_t audio_stop_handler(httpd_req_t *req);
esp_err_t audio_pause_handler(httpd_req_t *req);
esp_err_t audio_resume_handler(httpd_req_t *req);
esp_err_t audio_volume_handler(httpd_req_t *req);
esp_err_t audio_seek_handler(httpd_req_t *req);
esp_err_t ping_handler(httpd_req_t *req);
esp_err_t wifi_scan_handler(httpd_req_t *req);
esp_err_t wifi_config_handler(httpd_req_t *req);
esp_err_t mqtt_config_handler(httpd_req_t *req);
esp_err_t logging_config_handler(httpd_req_t *req);
esp_err_t mqtt_users_handler(httpd_req_t *req);
esp_err_t publish_handler(httpd_req_t *req);
esp_err_t ap_stop_handler(httpd_req_t *req);
esp_err_t root_get_handler(httpd_req_t *req);
esp_err_t gm_page_handler(httpd_req_t *req);
esp_err_t gm_state_handler(httpd_req_t *req);
esp_err_t gm_system_summary_handler(httpd_req_t *req);
esp_err_t gm_versions_handler(httpd_req_t *req);
esp_err_t gm_rooms_handler(httpd_req_t *req);
esp_err_t gm_room_save_handler(httpd_req_t *req);
esp_err_t gm_room_delete_handler(httpd_req_t *req);
esp_err_t gm_room_profiles_handler(httpd_req_t *req);
esp_err_t gm_room_profile_select_handler(httpd_req_t *req);
esp_err_t gm_room_profile_save_handler(httpd_req_t *req);
esp_err_t gm_room_profile_delete_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_select_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_editor_catalog_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_validate_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_save_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_delete_handler(httpd_req_t *req);
esp_err_t gm_room_runtime_state_handler(httpd_req_t *req);
esp_err_t gm_rooms_runtime_summary_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_start_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_stop_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_next_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_approve_handler(httpd_req_t *req);
esp_err_t gm_room_scenario_reset_handler(httpd_req_t *req);
esp_err_t gm_room_game_start_handler(httpd_req_t *req);
esp_err_t gm_room_game_stop_handler(httpd_req_t *req);
esp_err_t gm_room_game_reset_handler(httpd_req_t *req);
esp_err_t gm_room_scenarios_export_handler(httpd_req_t *req);
esp_err_t gm_room_scenarios_import_handler(httpd_req_t *req);
esp_err_t gm_room_scenarios_save_handler(httpd_req_t *req);
esp_err_t gm_room_scenarios_load_handler(httpd_req_t *req);
esp_err_t gm_profiles_export_handler(httpd_req_t *req);
esp_err_t gm_profiles_import_handler(httpd_req_t *req);
esp_err_t gm_profiles_save_handler(httpd_req_t *req);
esp_err_t gm_profiles_load_handler(httpd_req_t *req);
esp_err_t gm_quest_devices_handler(httpd_req_t *req);
esp_err_t gm_quest_device_save_handler(httpd_req_t *req);
esp_err_t gm_quest_device_delete_handler(httpd_req_t *req);
esp_err_t gm_quest_device_command_run_handler(httpd_req_t *req);
esp_err_t gm_quest_devices_export_handler(httpd_req_t *req);
esp_err_t gm_quest_devices_import_handler(httpd_req_t *req);
esp_err_t gm_quest_devices_save_handler(httpd_req_t *req);
esp_err_t gm_quest_devices_load_handler(httpd_req_t *req);
esp_err_t gm_sidebar_presets_handler(httpd_req_t *req);
esp_err_t gm_sidebar_presets_save_handler(httpd_req_t *req);
esp_err_t gm_sidebar_presets_load_handler(httpd_req_t *req);
esp_err_t gm_sidebar_presets_export_handler(httpd_req_t *req);
esp_err_t gm_sidebar_presets_import_handler(httpd_req_t *req);
esp_err_t gm_room_scenarios_handler(httpd_req_t *req);
esp_err_t orchestrator_describe_interface_handler(httpd_req_t *req);
esp_err_t orchestrator_audit_recent_handler(httpd_req_t *req);
esp_err_t orchestrator_timeline_recent_handler(httpd_req_t *req);
esp_err_t orchestrator_control_devices_handler(httpd_req_t *req);
esp_err_t gm_timer_start_handler(httpd_req_t *req);
esp_err_t gm_timer_pause_handler(httpd_req_t *req);
esp_err_t gm_timer_resume_handler(httpd_req_t *req);
esp_err_t gm_timer_reset_handler(httpd_req_t *req);
esp_err_t gm_timer_add_handler(httpd_req_t *req);
esp_err_t gm_session_finish_handler(httpd_req_t *req);
esp_err_t gm_hint_send_handler(httpd_req_t *req);
esp_err_t gm_hint_clear_handler(httpd_req_t *req);
esp_err_t hardware_io_status_handler(httpd_req_t *req);
esp_err_t hardware_io_io_mode_handler(httpd_req_t *req);
