#pragma once

#define NODE_ID_MAX_LEN 32
#define NODE_NAME_MAX_LEN 48
#define NODE_WIFI_SSID_MAX_LEN 32
#define NODE_WIFI_PASSWORD_MAX_LEN 64
#define NODE_HOST_MAX_LEN 64
#define NODE_MQTT_CLIENT_ID_MAX_LEN 48

#define NODE_RELAY_MAX 8
#define NODE_MOSFET_MAX 8
#define NODE_UNIVERSAL_IO_MAX 8
#define NODE_LED_STRIP_MAX 2

#define NODE_INPUT_DEBOUNCE_MAX_MS 5000

#define NODE_DEVICE_DESCRIPTION_MAX_LEN 12288
#define NODE_CONTROL_DATA_JSON_MAX_LEN (NODE_DEVICE_DESCRIPTION_MAX_LEN + 256)
#define NODE_MQTT_PAYLOAD_MAX_LEN 14336

#define NODE_RULE_BUNDLE_STORE_MAX_LEN 32768
#define NODE_RULE_BUNDLE_HTTP_MAX_LEN 32768
#define NODE_RULE_BUNDLE_MQTT_MAX_LEN 8192
#define NODE_RULE_BUNDLE_GET_RESPONSE_MAX_LEN 32768
#define NODE_RULE_BUNDLE_MAX_LEN NODE_RULE_BUNDLE_STORE_MAX_LEN
#define NODE_RULE_BUNDLE_ID_MAX_LEN 48
#define NODE_RULE_MODE_MAX_LEN 16
#define NODE_RULE_API_ERROR_MAX_LEN 32
#define NODE_RULE_MAX_RULES 32
#define NODE_RULE_MAX_ACTIONS_TOTAL 128
#define NODE_RULE_MAX_ACTIONS_PER_RULE 12
#define NODE_RULE_MAX_ACTION_NESTING 4
#define NODE_RULE_MAX_EMIT_EVENTS 32
#define NODE_RULE_MAX_LOCAL_EVENTS 64
#define NODE_RULE_MAX_STATE_KEYS 32
#define NODE_RULE_STATE_KEY_MAX_LEN 32
#define NODE_RULE_MAX_TIMERS 16
#define NODE_RULE_TIMER_NAME_MAX_LEN 32
#define NODE_RULE_MAX_PHASES 16
#define NODE_RULE_PHASE_NAME_MAX_LEN 24
#define NODE_RULE_MAX_GROUP_INPUTS 8
#define NODE_RULE_MAX_EXPORT_COMMANDS 8
#define NODE_RULE_MAX_EXPORT_EVENTS 16
#define NODE_RULE_MAX_EXPORT_CLAIMS 4
#define NODE_RULE_EXPORT_LABEL_MAX_LEN 32

#define NODE_DRIVER_INSTANCE_MAX 4
#define NODE_DRIVER_ID_MAX_LEN 32
#define NODE_DRIVER_IMPL_MAX_LEN 16
#define NODE_DRIVER_BUS_MAX_LEN 16
#define NODE_DRIVER_EVENT_NAME_MAX_LEN 48
#define NODE_DRIVER_UID_TEXT_MAX_LEN 24
#define NODE_DRIVER_NFC_KNOWN_CARD_MAX 16

#define NODE_RESET_WIFI_HOLD_MS 5000
#define NODE_FACTORY_RESET_HOLD_MS 30000
