#pragma once

#define NODE_ID_MAX_LEN 32
#define NODE_NAME_MAX_LEN 48
#define NODE_WIFI_SSID_MAX_LEN 32
#define NODE_WIFI_PASSWORD_MAX_LEN 64
#define NODE_HOST_MAX_LEN 64
#define NODE_MQTT_CLIENT_ID_MAX_LEN 48

#define NODE_RELAY_MAX 8
#define NODE_MOSFET_MAX 8
#define NODE_UNIVERSAL_IO_MAX 8
#define NODE_LED_STRIP_MAX 2

#define NODE_DEVICE_DESCRIPTION_MAX_LEN 4096
#define NODE_CONTROL_DATA_JSON_MAX_LEN (NODE_DEVICE_DESCRIPTION_MAX_LEN + 96)
#define NODE_MQTT_PAYLOAD_MAX_LEN 6144

#define NODE_RESET_WIFI_HOLD_MS 5000
#define NODE_FACTORY_RESET_HOLD_MS 30000
