#include "node_provisioning_internal.h"

esp_err_t node_provisioning_ui_root_get(httpd_req_t *req)
{
    static const char body[] =
        "<!doctype html><html><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>SceneHub Node Setup</title>"
        "<style>"
        ":root{--bg:#07111d;--card:#0d1b2b;--line:#24415f;--muted:#9eb8d6;--text:#e8f2ff;--accent:#2b8df0;--danger:#b53333}"
        "*{box-sizing:border-box}body{font-family:system-ui,sans-serif;background:var(--bg);color:var(--text);margin:0;padding:20px}"
        "main{max-width:900px;margin:auto;background:var(--card);border:1px solid var(--line);border-radius:16px;padding:18px}"
        "h1{margin:0 0 12px}h2{margin:14px 0 10px;font-size:18px}label{display:block;margin:12px 0 6px;color:var(--muted);font-size:13px}"
        "input,select{width:100%;border:1px solid #274a6d;background:#081421;color:#fff;border-radius:10px;padding:10px}"
        ".tabs{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.tab{border:1px solid #295072;background:#0a1624;color:#cfe8ff;border-radius:999px;padding:9px 12px;font-weight:700}"
        ".tab.active{background:var(--accent);color:#fff}.panel{display:none}.panel.active{display:block}"
        ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.pin{border:1px solid #203a58;border-radius:12px;padding:12px;background:#091726}"
        ".pin h3{margin:0 0 8px;font-size:15px}.actions{margin-top:14px}button{border:0;border-radius:10px;background:#1d75d8;color:#fff;padding:10px 14px;margin:8px 8px 0 0;font-weight:700}"
        "button.danger{background:var(--danger)}pre{white-space:pre-wrap;background:#06101b;border-radius:10px;padding:10px;color:#b9d3ee;min-height:44px}"
        ".hint{color:var(--muted);font-size:13px}.locked{opacity:.55}"
        "</style></head><body><main>"
        "<h1>SceneHub Node Setup</h1>"
        "<div class='tabs'>"
        "<button class='tab active' data-tab='network' onclick=\"showTab('network')\">Network</button>"
        "<button class='tab' data-tab='relay' onclick=\"showTab('relay')\">Relay</button>"
        "<button class='tab' data-tab='mosfet' onclick=\"showTab('mosfet')\">MOSFET</button>"
        "<button class='tab' data-tab='io' onclick=\"showTab('io')\">IO</button>"
        "<button class='tab' data-tab='led' onclick=\"showTab('led')\">LED</button>"
        "</div>"
        "<section id='tab_network' class='panel active'>"
        "<h2>Identity and network</h2><div class='grid'>"
        "<div><label>Node ID</label><input id='node_id'></div>"
        "<div><label>Node name</label><input id='node_name'></div>"
        "<div><label>Wi-Fi SSID</label><input id='wifi_ssid'></div>"
        "<div><label>Wi-Fi password</label><input id='wifi_password' type='password'></div>"
        "<div><label>SceneHub host/IP</label><input id='controller_host'></div>"
        "<div><label>MQTT port</label><input id='mqtt_port' type='number'></div>"
        "<div><label>MQTT client ID</label><input id='mqtt_client_id'></div>"
        "<div><label>Reset GPIO</label><input id='reset_gpio' type='number'></div>"
        "</div></section>"
        "<section id='tab_relay' class='panel'><h2>Relay pins</h2><div id='relay_rows' class='grid'></div></section>"
        "<section id='tab_mosfet' class='panel'><h2>MOSFET pins</h2><div id='mosfet_rows' class='grid'></div></section>"
        "<section id='tab_io' class='panel'><h2>Universal IO pins</h2><p class='hint'>Role: disabled, input or output.</p><div id='io_rows' class='grid'></div></section>"
        "<section id='tab_led' class='panel'><h2>LED strip pins</h2><div id='led_rows' class='grid'></div></section>"
        "<div class='actions'>"
        "<button onclick='saveCfg()'>Save config</button><button onclick='restart()'>Restart</button>"
        "<button class='danger' onclick='resetWifi()'>Reset Wi-Fi</button><button class='danger' onclick='factoryReset()'>Factory reset</button>"
        "</div><pre id='status'>Loading...</pre>"
        "<script>"
        "async function api(u,o){let r=await fetch(u,o);let t=await r.text();if(!r.ok)throw new Error(t);return t?JSON.parse(t):{}}"
        "let current={};function el(id){return document.getElementById(id)}function v(id){return el(id).value}function b(id){return el(id).checked}"
        "function status(x){el('status').textContent=typeof x==='string'?x:JSON.stringify(x,null,2)}"
        "function showTab(name){document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab===name));el('tab_'+name).classList.add('active')}"
        "async function load(){current=await api('/api/config');for(let k of ['node_id','node_name','wifi_ssid','controller_host','mqtt_client_id'])el(k).value=current[k]||'';el('mqtt_port').value=current.mqtt_port||1883;el('reset_gpio').value=current.reset_gpio??0;renderPins(current);status('Loaded')}"
        "function cfg(){let o={node_id:v('node_id'),node_name:v('node_name'),wifi_ssid:v('wifi_ssid'),controller_host:v('controller_host'),mqtt_port:Number(v('mqtt_port')||1883),mqtt_client_id:v('mqtt_client_id'),reset_gpio:Number(v('reset_gpio')||0)};let wp=v('wifi_password');if(wp)o.wifi_password=wp;collectPins(o);return o}"
        "function pinShell(prefix,i,p,inner){let n=i+1;let gpio=(p.gpio===undefined||p.gpio===null)?-1:p.gpio;return `<div class='pin'><h3>${prefix.toUpperCase()} ${n}</h3><label><input type='checkbox' id='${prefix}${n}_enabled' ${p.enabled?'checked':''}> enabled</label><label>GPIO</label><input id='${prefix}${n}_gpio' type='number' value='${gpio}'><label>Label</label><input id='${prefix}${n}_label' value='${p.label||''}'>${inner||''}</div>`}"
        "function outputPin(prefix,i,p){return pinShell(prefix,i,p,`<label><input type='checkbox' id='${prefix}${i+1}_active_low' ${p.active_low?'checked':''}> active low</label>`)}"
        "function ioPin(i,p){return pinShell('io',i,p,`<label>Role</label><select id='io${i+1}_role'><option value='0'>disabled</option><option value='3'>input</option><option value='4'>output</option></select><label><input type='checkbox' id='io${i+1}_active_low' ${p.active_low?'checked':''}> active low</label>`)}"
        "function ledPin(i,p){return pinShell('led',i,p,`<label>Pixels</label><input id='led${i+1}_pixel_count' type='number' value='${p.pixel_count||30}'>`)}"
        "function renderPins(c){el('relay_rows').innerHTML=(c.relays||[]).map((p,i)=>outputPin('relay',i,p)).join('');el('mosfet_rows').innerHTML=(c.mosfets||[]).map((p,i)=>outputPin('mosfet',i,p)).join('');el('io_rows').innerHTML=(c.universal_io||[]).map((p,i)=>ioPin(i,p)).join('');el('led_rows').innerHTML=(c.led_strips||[]).map((p,i)=>ledPin(i,p)).join('');(c.universal_io||[]).forEach((p,i)=>{el(`io${i+1}_role`).value=String(p.role||0)});if(c.pin_config_locked){['relay','mosfet','io','led'].forEach(n=>el('tab_'+n).classList.add('locked'));document.querySelectorAll('#tab_relay input,#tab_mosfet input,#tab_io input,#tab_io select,#tab_led input').forEach(x=>x.disabled=true)}}"
        "function collectPins(o){if(current.pin_config_locked)return;['relay','mosfet'].forEach(prefix=>{for(let i=1;i<=8;i++){o[`${prefix}${i}_enabled`]=b(`${prefix}${i}_enabled`);o[`${prefix}${i}_gpio`]=Number(v(`${prefix}${i}_gpio`)||-1);o[`${prefix}${i}_active_low`]=b(`${prefix}${i}_active_low`);o[`${prefix}${i}_label`]=v(`${prefix}${i}_label`)}});for(let i=1;i<=8;i++){o[`io${i}_enabled`]=b(`io${i}_enabled`);o[`io${i}_gpio`]=Number(v(`io${i}_gpio`)||-1);o[`io${i}_role`]=Number(v(`io${i}_role`)||0);o[`io${i}_active_low`]=b(`io${i}_active_low`);o[`io${i}_label`]=v(`io${i}_label`)}for(let i=1;i<=2;i++){o[`led${i}_enabled`]=b(`led${i}_enabled`);o[`led${i}_gpio`]=Number(v(`led${i}_gpio`)||-1);o[`led${i}_pixel_count`]=Number(v(`led${i}_pixel_count`)||30);o[`led${i}_label`]=v(`led${i}_label`)}}"
        "async function saveCfg(){try{status(await api('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(cfg())}))}catch(e){status(e.message)}}"
        "async function restart(){await api('/api/restart',{method:'POST'});status('Restarting...')}"
        "async function resetWifi(){if(confirm('Reset Wi-Fi settings?'))status(await api('/api/reset-wifi',{method:'POST'}))}"
        "async function factoryReset(){if(confirm('Factory reset all node config?'))status(await api('/api/factory-reset',{method:'POST'}))}"
        "load().catch(e=>status(e.message));"
        "</script></main></body></html>";
    httpd_resp_set_type(req, "text/html");
    return httpd_resp_send(req, body, HTTPD_RESP_USE_STRLEN);
}
