#pragma once

#include "sdkconfig.h"

/*
 * Build-time SceneHub fallbacks live here so component tests and reduced
 * builds remain predictable when a Kconfig symbol is absent. Hardware outputs
 * default to disabled in that case.
 */

#ifndef CONFIG_SCENEHUB_AUDIO_OUTPUT_DRIVER_PCM5102A
#define CONFIG_SCENEHUB_AUDIO_OUTPUT_DRIVER_PCM5102A 0
#endif
#ifndef CONFIG_SCENEHUB_AUDIO_OUTPUT_DRIVER_MAX98357A
#define CONFIG_SCENEHUB_AUDIO_OUTPUT_DRIVER_MAX98357A 1
#endif
#ifndef CONFIG_SCENEHUB_MAX98357A_SD_MODE_GPIO
#define CONFIG_SCENEHUB_MAX98357A_SD_MODE_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_I2S_BCK_PIN
#define CONFIG_SCENEHUB_I2S_BCK_PIN 4
#endif
#ifndef CONFIG_SCENEHUB_I2S_WS_PIN
#define CONFIG_SCENEHUB_I2S_WS_PIN 5
#endif
#ifndef CONFIG_SCENEHUB_I2S_DATA_PIN
#define CONFIG_SCENEHUB_I2S_DATA_PIN 6
#endif

#ifndef CONFIG_SCENEHUB_SD_MISO_PIN
#define CONFIG_SCENEHUB_SD_MISO_PIN 13
#endif
#ifndef CONFIG_SCENEHUB_SD_MOSI_PIN
#define CONFIG_SCENEHUB_SD_MOSI_PIN 11
#endif
#ifndef CONFIG_SCENEHUB_SD_CLK_PIN
#define CONFIG_SCENEHUB_SD_CLK_PIN 12
#endif
#ifndef CONFIG_SCENEHUB_SD_CS_PIN
#define CONFIG_SCENEHUB_SD_CS_PIN 10
#endif

#ifndef CONFIG_SCENEHUB_MQTT_MAX_CLIENTS
#define CONFIG_SCENEHUB_MQTT_MAX_CLIENTS 25
#endif
#ifndef CONFIG_SCENEHUB_MAX_ROOMS
#define CONFIG_SCENEHUB_MAX_ROOMS 1
#endif
#ifndef CONFIG_SCENEHUB_EVENT_BUS_SKIP_EVENT_VALIDATION
#define CONFIG_SCENEHUB_EVENT_BUS_SKIP_EVENT_VALIDATION 0
#endif
#ifndef CONFIG_SCENEHUB_SETUP_AP_PASSWORD
#define CONFIG_SCENEHUB_SETUP_AP_PASSWORD "12345678"
#endif
#ifndef CONFIG_SCENEHUB_WEB_AUTH_DEFAULT_USER
#define CONFIG_SCENEHUB_WEB_AUTH_DEFAULT_USER "admin"
#endif
#ifndef CONFIG_SCENEHUB_WEB_AUTH_DEFAULT_PASS
#define CONFIG_SCENEHUB_WEB_AUTH_DEFAULT_PASS "admin"
#endif
#ifndef CONFIG_SCENEHUB_WEB_AUTH_RESET_GPIO
#define CONFIG_SCENEHUB_WEB_AUTH_RESET_GPIO -1
#endif

#ifndef CONFIG_SCENEHUB_RELAY1_GPIO
#define CONFIG_SCENEHUB_RELAY1_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_RELAY2_GPIO
#define CONFIG_SCENEHUB_RELAY2_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_RELAY3_GPIO
#define CONFIG_SCENEHUB_RELAY3_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_RELAY4_GPIO
#define CONFIG_SCENEHUB_RELAY4_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_RELAY_ACTIVE_LOW
#define CONFIG_SCENEHUB_RELAY_ACTIVE_LOW 1
#endif
#ifndef CONFIG_SCENEHUB_RELAY_MAX_PULSE_MS
#define CONFIG_SCENEHUB_RELAY_MAX_PULSE_MS 60000
#endif

#ifndef CONFIG_SCENEHUB_MOSFET1_GPIO
#define CONFIG_SCENEHUB_MOSFET1_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_MOSFET2_GPIO
#define CONFIG_SCENEHUB_MOSFET2_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_MOSFET3_GPIO
#define CONFIG_SCENEHUB_MOSFET3_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_MOSFET4_GPIO
#define CONFIG_SCENEHUB_MOSFET4_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_MOSFET_PWM_FREQ_HZ
#define CONFIG_SCENEHUB_MOSFET_PWM_FREQ_HZ 1000
#endif
#ifndef CONFIG_SCENEHUB_MOSFET_MAX_PULSE_MS
#define CONFIG_SCENEHUB_MOSFET_MAX_PULSE_MS 60000
#endif
#ifndef CONFIG_SCENEHUB_MOSFET_MAX_FADE_MS
#define CONFIG_SCENEHUB_MOSFET_MAX_FADE_MS 60000
#endif

#ifndef CONFIG_SCENEHUB_GPIO1_GPIO
#define CONFIG_SCENEHUB_GPIO1_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_GPIO2_GPIO
#define CONFIG_SCENEHUB_GPIO2_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_GPIO3_GPIO
#define CONFIG_SCENEHUB_GPIO3_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_GPIO4_GPIO
#define CONFIG_SCENEHUB_GPIO4_GPIO -1
#endif
#ifndef CONFIG_SCENEHUB_GPIO1_MODE
#define CONFIG_SCENEHUB_GPIO1_MODE 0
#endif
#ifndef CONFIG_SCENEHUB_GPIO2_MODE
#define CONFIG_SCENEHUB_GPIO2_MODE 0
#endif
#ifndef CONFIG_SCENEHUB_GPIO3_MODE
#define CONFIG_SCENEHUB_GPIO3_MODE 0
#endif
#ifndef CONFIG_SCENEHUB_GPIO4_MODE
#define CONFIG_SCENEHUB_GPIO4_MODE 0
#endif
#ifndef CONFIG_SCENEHUB_GPIO_ACTIVE_LOW
#define CONFIG_SCENEHUB_GPIO_ACTIVE_LOW 0
#endif
#ifndef CONFIG_SCENEHUB_GPIO_PULLUP
#define CONFIG_SCENEHUB_GPIO_PULLUP 0
#endif
#ifndef CONFIG_SCENEHUB_GPIO_PULLDOWN
#define CONFIG_SCENEHUB_GPIO_PULLDOWN 0
#endif
#ifndef CONFIG_SCENEHUB_GPIO_DEBOUNCE_MS
#define CONFIG_SCENEHUB_GPIO_DEBOUNCE_MS 30
#endif
#ifndef CONFIG_SCENEHUB_GPIO_MAX_PULSE_MS
#define CONFIG_SCENEHUB_GPIO_MAX_PULSE_MS 60000
#endif
#ifndef CONFIG_SCENEHUB_HARDWARE_MAX_EFFECT_MS
#define CONFIG_SCENEHUB_HARDWARE_MAX_EFFECT_MS 600000
#endif
